{application,brain,
             [{description,"The brain is a distributed Tuplespace"},
              {vsn,"0.0.2"},
              {registered,[brain]},
              {applications,[kernel,stdlib]},
              {mod,{brain_app,[]}},
              {env,[]},
              {modules,[brain_app,brain_sup,gen_reactor,reactor,
                        simple_reactor,tuple_space,tuple_space_server,
                        utilities]}]}.
